services:
  websocket-server:
    container_name: websocket-server
    build: .
    environment:
      DATABASE_URL: "host=event_db user=root password=password dbname=event sslmode=disable"
      KAFKA_BROKER: localhost:9092

    ports:
      - "8083:8083"
    depends_on:
      - event_db
      - kafka
  event_db:
    container_name: event_db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: event
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

volumes:
    pgdata: { }
